// <auto-generated />
using System;
using BepNha.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BepNha.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416025838_kjflsa")]
    partial class kjflsa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BepNha.Web.Models.Entities.BookingStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("BookingStatusLogs");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRwN9aL-rWiE84uhQtFyiGpEQuuzuFr4-5eN1EtrkwsIuqONeqYfnTkUTrcQAY1ykWJLTure1CWATyo9lijssqG4d7co0-XhGE2gHUuIE&s=10",
                            IsAvailable = true,
                            Name = "Phở Bò Gia Truyền",
                            Price = 60000m,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5WYtKbS5Wlhs3rqXiWFxQ-uNQclEFsIK-0dGvaSi-QQISpMcVH6blrc4YHTTbrJxPbcx09HLYvQdcT6MTEQ8pDLCMCPAjpfhoLdG4xg&s=10",
                            IsAvailable = true,
                            Name = "Bún Chả Hà Nội",
                            Price = 55000m,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTf1O9yeFBadtoTsTJOyWoO5MwsJQtA-Tey3JKHa1DR-hbBdw3slSfSPa6jSjIW3j2GILtXt0IugS4DFkIDx7S6ObmkcSzdLmin1_iTw&s=10",
                            IsAvailable = true,
                            Name = "Bánh Mỳ Đặc Biệt",
                            Price = 35000m,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepQeDdO_6TRDmHskInYem6d7DYmSqTMyFkY-tUA8LD6zR_3C5eQ15yCxUicNBeVVy9pIEuTJRp6Wcx8BJm5OxXNztW9MUE1mRvSzSajlbtT1AWxc3MPDpVsZ6bmvXR3qZUgGNfoDg=w260-h175-n-k-no",
                            IsAvailable = true,
                            Name = "Cơm Tấm Sườn Bì",
                            Price = 65000m,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://vietnhatplastic.com/Data/Sites/1/News/294/cach-lam-nem-cuon-4.jpg",
                            IsAvailable = true,
                            Name = "Nem Cuốn Tươi",
                            Price = 40000m,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.NbE2a1R238JYyH0bb1nfXQHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsAvailable = true,
                            Name = "Gỏi Cuốn Tôm Thịt",
                            Price = 45000m,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://th.bing.com/th/id/R.57096e43c834470d570dde5833ae5572?rik=7fqpfOL7A9rdGg&pid=ImgRaw&r=0",
                            IsAvailable = true,
                            Name = "Bún Bò Huế",
                            Price = 60000m,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://tse3.mm.bing.net/th/id/OIP.b6kfLQ84fnq5Kc-q4V2d1QHaEZ?rs=1&pid=ImgDetMain&o=7&rm=3",
                            IsAvailable = true,
                            Name = "Chả Giò Rán",
                            Price = 35000m,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://cdn.tgdd.vn/2021/01/CookProduct/1200fgsd-1200x675.jpg",
                            IsAvailable = true,
                            Name = "Mì Quảng Tôm Thịt",
                            Price = 55000m,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Category = "Món chính",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://file.hstatic.net/200000700229/article/com-ga-chien-mam-toi-1_598c51ff37f84acd99f186d64e0acba0.jpg",
                            IsAvailable = true,
                            Name = "Cơm Gà Hội An",
                            Price = 65000m,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCZXv8SZ-pB6Qf686UrKMTXvt1-nLP8WSVzg&s",
                            IsAvailable = true,
                            Name = "Cà Phê Sữa Đá",
                            Price = 25000m,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://horecavn.com/wp-content/uploads/2024/05/bac-xiu-da_20240527105417.jpg",
                            IsAvailable = true,
                            Name = "Bạc Xỉu",
                            Price = 28000m,
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 13,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://dayphache.edu.vn/wp-content/uploads/2024/06/cach-lam-tra-dao.jpg",
                            IsAvailable = true,
                            Name = "Trà Đào Cam Sả",
                            Price = 45000m,
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 14,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://product.hstatic.net/200000723779/product/e1b07ac46dcb4bdd835ec1e98cd4cf83_d1bc01a388704ddd8539a59a8dd6a7b2_grande.jpg",
                            IsAvailable = true,
                            Name = "Nước Ép Cam Tươi",
                            Price = 35000m,
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 15,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://tmart.nanoweb.vn/public/uploads/all/kHrlDUmImj7pEVSr0QpAOGR4oMIOC7rWbaRvpMmx.png",
                            IsAvailable = true,
                            Name = "Trà Sữa Trân Châu",
                            Price = 40000m,
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 16,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQie4Hw_GApMLyRn34hNhlXh46_33_56ZcfMA&s",
                            IsAvailable = true,
                            Name = "Sinh Tố Bơ",
                            Price = 45000m,
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 17,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://congthucphache.com/wp-content/uploads/2019/03/CONG-THUC-PHA-CHE-CHANH-DAY-TUYET-PASSION-SNOW.jpg",
                            IsAvailable = true,
                            Name = "Chanh Dây Tuyết",
                            Price = 30000m,
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 18,
                            Category = "Đồ uống",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImageUrl = "https://www.unileverfoodsolutions.com.vn/dam/global-ufs/mcos/phvn/vietnam/calcmenu/recipes/VN-recipes/other/sweet-lychee-tea/main-header.jpg",
                            IsAvailable = true,
                            Name = "Trà Vải",
                            Price = 42000m,
                            SortOrder = 18
                        });
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.OrderStatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusLogs");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("TableCode")
                        .IsUnique();

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_01"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_02"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_03"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 6,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_04"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 6,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_05"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 8,
                            IsActive = true,
                            Status = "available",
                            TableCode = "BAN_06"
                        });
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.TableBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("CustomerPhone");

                    b.HasIndex("TableId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("TableBookings");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeOnly(10, 0, 0),
                            IsActive = true,
                            MaxCapacity = 20,
                            SlotName = "Sáng (7:00 - 10:00)",
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeOnly(14, 0, 0),
                            IsActive = true,
                            MaxCapacity = 30,
                            SlotName = "Trưa (11:00 - 14:00)",
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeOnly(17, 0, 0),
                            IsActive = true,
                            MaxCapacity = 20,
                            SlotName = "Chiều (14:00 - 17:00)",
                            StartTime = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeOnly(21, 0, 0),
                            IsActive = true,
                            MaxCapacity = 30,
                            SlotName = "Tối (17:00 - 21:00)",
                            StartTime = new TimeOnly(17, 0, 0)
                        });
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Quản trị viên",
                            IsActive = true,
                            Password = "$2a$11$IluMistMhfEaEuEKe1Sz0exsYOLJh55mO6NQWqkf8cKWAzN3Ss.l6",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Nhân viên bếp",
                            IsActive = true,
                            Password = "$2a$11$SY.Z7lA3kB.JmMJr/Y1X8eyK8AD3wIpjVIxf6Xkox7loTrxjj2btu",
                            Role = "Staff",
                            Username = "bep01"
                        });
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.BookingStatusLog", b =>
                {
                    b.HasOne("BepNha.Web.Models.Entities.TableBooking", "Booking")
                        .WithMany("StatusLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepNha.Web.Models.Entities.User", "ChangedByUser")
                        .WithMany("BookingStatusLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.Order", b =>
                {
                    b.HasOne("BepNha.Web.Models.Entities.User", "ConfirmedByUser")
                        .WithMany("ConfirmedOrders")
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BepNha.Web.Models.Entities.TimeSlot", "TimeSlot")
                        .WithMany("Orders")
                        .HasForeignKey("TimeSlotId");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("BepNha.Web.Models.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BepNha.Web.Models.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.OrderStatusLog", b =>
                {
                    b.HasOne("BepNha.Web.Models.Entities.User", "ChangedByUser")
                        .WithMany("OrderStatusLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BepNha.Web.Models.Entities.Order", "Order")
                        .WithMany("StatusLogs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.TableBooking", b =>
                {
                    b.HasOne("BepNha.Web.Models.Entities.User", "ConfirmedByUser")
                        .WithMany("ConfirmedBookings")
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BepNha.Web.Models.Entities.Table", "Table")
                        .WithMany("TableBookings")
                        .HasForeignKey("TableId");

                    b.HasOne("BepNha.Web.Models.Entities.TimeSlot", "TimeSlot")
                        .WithMany("TableBookings")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Table");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.Table", b =>
                {
                    b.Navigation("TableBookings");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.TableBooking", b =>
                {
                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.TimeSlot", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TableBookings");
                });

            modelBuilder.Entity("BepNha.Web.Models.Entities.User", b =>
                {
                    b.Navigation("BookingStatusLogs");

                    b.Navigation("ConfirmedBookings");

                    b.Navigation("ConfirmedOrders");

                    b.Navigation("OrderStatusLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
